apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-weather-pod
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: weather-api-key  # Name of the secret
                  key: APIKEY            # Key within the secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}  # Assuming you have defined resources in values.yaml
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}  # Optional: Add liveness probe if defined
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}  # Optional: Add readiness probe if defined
