apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-weather-pod
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}  # Ensure this matches the existing deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: weather-api-key      # Secret name
                  key: APIKEY                # Key within the secret
